name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Load .env file
      run: |
        if [ -f .env ]; then
          export $(cat .env | xargs)
        fi

    - name: Run unit tests
      run: npm test

    - name: Lint code
      run: npm run lint

    - name: Start server
      run: node server.js
      env:
        PORT: ${{ env.PORT }}
        DB_CONNECTION_STRING: ${{ env.DB_CONNECTION_STRING }}
        TMDB_API_KEY: ${{ env.TMDB_API_KEY }}
